services:
  s1ds:
    image: s1ds:local
    container_name: s1ds
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "38465:38465/udp"
      - "38465:38465/tcp"
      - "27016:27016/udp"
    volumes:
      - s1ds_game:/home/steam/game
      - s1ds_steamcmd:/home/steam/steamcmd
      - s1ds_steam_home:/home/steam/Steam

volumes:
  s1ds_game:
  s1ds_steamcmd:
  s1ds_steam_home:
