using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace DedicatedServerMod.Shared.ModVerification
{
    /// <summary>
    /// Describes a loaded client-side Melon mod reported during join verification.
    /// </summary>
    /// <remarks>
    /// This payload is sent by the dedicated client runtime during the pre-join verification handshake.
    /// Mod authors normally do not construct this type manually.
    /// </remarks>
    [Serializable]
    public sealed class ClientModDescriptor
    {
        /// <summary>
        /// Stable mod identifier declared by <c>S1DSClientModIdentityAttribute</c>, when present.
        /// </summary>
        [JsonProperty("modId")]
        public string ModId { get; set; } = string.Empty;

        /// <summary>
        /// Client mod version string.
        /// </summary>
        [JsonProperty("version")]
        public string Version { get; set; } = string.Empty;

        /// <summary>
        /// Human-readable display name.
        /// </summary>
        [JsonProperty("displayName")]
        public string DisplayName { get; set; } = string.Empty;

        /// <summary>
        /// Mod author string when available.
        /// </summary>
        [JsonProperty("author")]
        public string Author { get; set; } = string.Empty;

        /// <summary>
        /// Assembly file name or simple assembly name.
        /// </summary>
        [JsonProperty("assemblyName")]
        public string AssemblyName { get; set; } = string.Empty;

        /// <summary>
        /// SHA-256 hash of the mod assembly bytes.
        /// </summary>
        [JsonProperty("sha256")]
        public string Sha256 { get; set; } = string.Empty;

        /// <summary>
        /// Whether the mod explicitly declared its S1DS identity metadata.
        /// </summary>
        [JsonProperty("identityDeclared")]
        public bool IdentityDeclared { get; set; }
    }

    /// <summary>
    /// Server-to-client challenge payload for the mod verification handshake.
    /// </summary>
    /// <remarks>
    /// This is public so it appears in the generated API reference, but it is transport
    /// infrastructure for DedicatedServerMod rather than a general-purpose messaging contract.
    /// </remarks>
    [Serializable]
    public sealed class ModVerificationChallengeMessage
    {
        /// <summary>
        /// One-time nonce generated by the server.
        /// </summary>
        [JsonProperty("nonce")]
        public string Nonce { get; set; } = string.Empty;

        /// <summary>
        /// Timeout for the verification phase in seconds.
        /// </summary>
        [JsonProperty("timeoutSeconds")]
        public int TimeoutSeconds { get; set; }

        /// <summary>
        /// Protocol version for the verification payload shape.
        /// </summary>
        [JsonProperty("protocolVersion")]
        public string ProtocolVersion { get; set; } = "1";

        /// <summary>
        /// Hash of the active server verification policy snapshot.
        /// </summary>
        [JsonProperty("policyHash")]
        public string PolicyHash { get; set; } = string.Empty;
    }

    /// <summary>
    /// Client-to-server verification report payload.
    /// </summary>
    /// <remarks>
    /// This report contains all non-core Melon mods loaded by the dedicated client runtime.
    /// </remarks>
    [Serializable]
    public sealed class ModVerificationReportMessage
    {
        /// <summary>
        /// Challenge nonce echoed back by the client.
        /// </summary>
        [JsonProperty("nonce")]
        public string Nonce { get; set; } = string.Empty;

        /// <summary>
        /// All non-core client mods currently loaded by MelonLoader.
        /// </summary>
        [JsonProperty("mods")]
        public List<ClientModDescriptor> Mods { get; set; } = new List<ClientModDescriptor>();
    }

    /// <summary>
    /// Server-to-client result payload for mod verification.
    /// </summary>
    /// <remarks>
    /// The human-readable <see cref="Message"/> is intended to be shown directly to the user when join
    /// verification fails.
    /// </remarks>
    [Serializable]
    public sealed class ModVerificationResultMessage
    {
        /// <summary>
        /// Whether mod verification succeeded.
        /// </summary>
        [JsonProperty("success")]
        public bool Success { get; set; }

        /// <summary>
        /// Human-readable result or failure reason.
        /// </summary>
        [JsonProperty("message")]
        public string Message { get; set; } = string.Empty;
    }

    /// <summary>
    /// Configuration entry describing an approved unpaired client-only mod for strict mode.
    /// </summary>
    /// <remarks>
    /// Server owners place these entries in <c>client_mod_policy.json</c> when strict mode is enabled
    /// and they still want to allow specific client-only mods.
    /// </remarks>
    [Serializable]
    public sealed class ApprovedUnpairedClientModPolicyEntry
    {
        /// <summary>
        /// Stable client mod identifier when the mod declares one.
        /// </summary>
        [JsonProperty("modId")]
        public string ModId { get; set; } = string.Empty;

        /// <summary>
        /// Human-readable fallback name used when the mod does not declare an identifier.
        /// </summary>
        [JsonProperty("displayName")]
        public string DisplayName { get; set; } = string.Empty;

        /// <summary>
        /// Exact hashes accepted for the approved unpaired mod in strict mode.
        /// </summary>
        [JsonProperty("pinnedSha256")]
        public List<string> PinnedSha256 { get; set; } = new List<string>();
    }

    /// <summary>
    /// File-backed server policy for client mod verification.
    /// </summary>
    /// <remarks>
    /// This type maps directly to <c>client_mod_policy.json</c>. In the default compatibility-first
    /// mode, most paired mods are discovered automatically from server mod metadata, so server owners
    /// usually only need this file for deny lists or strict-mode overrides.
    /// </remarks>
    /// <example>
    /// <code>
    /// {
    ///   "deniedClientModIds": [ "example.badmod" ],
    ///   "deniedClientModNames": [ "Suspicious Visual Pack" ],
    ///   "deniedClientModHashes": [ "abcdef123456..." ],
    ///   "approvedUnpairedClientMods": [],
    ///   "strictPinnedCompanionHashes": {}
    /// }
    /// </code>
    /// </example>
    [Serializable]
    public sealed class ClientModPolicy
    {
        /// <summary>
        /// Explicitly denied client mod identifiers.
        /// </summary>
        [JsonProperty("deniedClientModIds")]
        public List<string> DeniedClientModIds { get; set; } = new List<string>();

        /// <summary>
        /// Explicitly denied client mod display names.
        /// </summary>
        [JsonProperty("deniedClientModNames")]
        public List<string> DeniedClientModNames { get; set; } = new List<string>();

        /// <summary>
        /// Explicitly denied client mod hashes.
        /// </summary>
        [JsonProperty("deniedClientModHashes")]
        public List<string> DeniedClientModHashes { get; set; } = new List<string>();

        /// <summary>
        /// Approved unpaired client-only mods for strict mode.
        /// </summary>
        [JsonProperty("approvedUnpairedClientMods")]
        public List<ApprovedUnpairedClientModPolicyEntry> ApprovedUnpairedClientMods { get; set; } = new List<ApprovedUnpairedClientModPolicyEntry>();

        /// <summary>
        /// Optional strict-mode hash overrides keyed by companion mod identifier.
        /// </summary>
        [JsonProperty("strictPinnedCompanionHashes")]
        public Dictionary<string, List<string>> StrictPinnedCompanionHashes { get; set; } =
            new Dictionary<string, List<string>>(StringComparer.OrdinalIgnoreCase);

        /// <summary>
        /// Normalizes the policy in-place for consistent comparisons.
        /// </summary>
        /// <remarks>
        /// This trims values, lowercases hashes, removes duplicates, and rebuilds the strict override map
        /// using case-insensitive keys.
        /// </remarks>
        public void Normalize()
        {
            DeniedClientModIds = NormalizeList(DeniedClientModIds);
            DeniedClientModNames = NormalizeList(DeniedClientModNames);
            DeniedClientModHashes = NormalizeHashes(DeniedClientModHashes);

            if (ApprovedUnpairedClientMods == null)
            {
                ApprovedUnpairedClientMods = new List<ApprovedUnpairedClientModPolicyEntry>();
            }

            foreach (ApprovedUnpairedClientModPolicyEntry entry in ApprovedUnpairedClientMods)
            {
                if (entry == null)
                {
                    continue;
                }

                entry.ModId = NormalizeValue(entry.ModId);
                entry.DisplayName = NormalizeValue(entry.DisplayName);
                entry.PinnedSha256 = NormalizeHashes(entry.PinnedSha256);
            }

            if (StrictPinnedCompanionHashes == null)
            {
                StrictPinnedCompanionHashes = new Dictionary<string, List<string>>(StringComparer.OrdinalIgnoreCase);
                return;
            }

            Dictionary<string, List<string>> normalized = new Dictionary<string, List<string>>(StringComparer.OrdinalIgnoreCase);
            foreach (KeyValuePair<string, List<string>> pair in StrictPinnedCompanionHashes)
            {
                string key = NormalizeValue(pair.Key);
                if (string.IsNullOrEmpty(key))
                {
                    continue;
                }

                normalized[key] = NormalizeHashes(pair.Value);
            }

            StrictPinnedCompanionHashes = normalized;
        }

        private static List<string> NormalizeList(List<string> values)
        {
            if (values == null)
            {
                return new List<string>();
            }

            HashSet<string> seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            List<string> normalized = new List<string>();
            for (int i = 0; i < values.Count; i++)
            {
                string value = NormalizeValue(values[i]);
                if (string.IsNullOrEmpty(value) || !seen.Add(value))
                {
                    continue;
                }

                normalized.Add(value);
            }

            return normalized;
        }

        private static List<string> NormalizeHashes(List<string> values)
        {
            if (values == null)
            {
                return new List<string>();
            }

            HashSet<string> seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            List<string> normalized = new List<string>();
            for (int i = 0; i < values.Count; i++)
            {
                string value = NormalizeHash(values[i]);
                if (string.IsNullOrEmpty(value) || !seen.Add(value))
                {
                    continue;
                }

                normalized.Add(value);
            }

            return normalized;
        }

        internal static string NormalizeValue(string value)
        {
            return string.IsNullOrWhiteSpace(value)
                ? string.Empty
                : value.Trim();
        }

        internal static string NormalizeHash(string value)
        {
            return string.IsNullOrWhiteSpace(value)
                ? string.Empty
                : value.Trim().ToLowerInvariant();
        }
    }

    internal sealed class DeclaredClientCompanionRequirement
    {
        public string ModId { get; set; } = string.Empty;

        public string DisplayName { get; set; } = string.Empty;

        public bool Required { get; set; }

        public string MinVersion { get; set; } = string.Empty;

        public List<string> PinnedSha256 { get; set; } = new List<string>();

        public string SourceAssemblyName { get; set; } = string.Empty;
    }
}
