using System;

namespace DedicatedServerMod.Shared.Networking
{
    /// <summary>
    /// Client-to-server authentication hello payload.
    /// </summary>
    [Serializable]
    public sealed class AuthHelloMessage
    {
        /// <summary>
        /// Mod version string reported by the client.
        /// </summary>
        public string Version { get; set; } = string.Empty;
    }

    /// <summary>
    /// Server-to-client authentication challenge payload.
    /// </summary>
    [Serializable]
    public sealed class AuthChallengeMessage
    {
        /// <summary>
        /// Authentication provider selected by server configuration.
        /// </summary>
        public string Provider { get; set; } = string.Empty;

        /// <summary>
        /// One-time nonce generated by server to bind challenge and response.
        /// </summary>
        public string Nonce { get; set; } = string.Empty;

        /// <summary>
        /// Timeout in seconds for the full authentication handshake.
        /// </summary>
        public int TimeoutSeconds { get; set; }

        /// <summary>
        /// Optional Steam Web API identity value used for web API ticket flow.
        /// </summary>
        public string WebApiIdentity { get; set; } = string.Empty;
    }

    /// <summary>
    /// Client-to-server authentication ticket submission payload.
    /// </summary>
    [Serializable]
    public sealed class AuthTicketMessage
    {
        /// <summary>
        /// Provider name that produced this ticket.
        /// </summary>
        public string Provider { get; set; } = string.Empty;

        /// <summary>
        /// Claimed client SteamID string.
        /// </summary>
        public string SteamId { get; set; } = string.Empty;

        /// <summary>
        /// Hex-encoded auth ticket bytes.
        /// </summary>
        public string TicketHex { get; set; } = string.Empty;

        /// <summary>
        /// Challenge nonce returned from server challenge.
        /// </summary>
        public string Nonce { get; set; } = string.Empty;
    }

    /// <summary>
    /// Server-to-client authentication result payload.
    /// </summary>
    [Serializable]
    public sealed class AuthResultMessage
    {
        /// <summary>
        /// Whether authentication succeeded.
        /// </summary>
        public bool Success { get; set; }

        /// <summary>
        /// Human-readable result message.
        /// </summary>
        public string Message { get; set; } = string.Empty;

        /// <summary>
        /// Trusted SteamID when authentication succeeds.
        /// </summary>
        public string SteamId { get; set; } = string.Empty;
    }
}
