apiRules:
- include:
    uidRegex: ^DedicatedServerMod\.API
    type: Namespace
- include:
    uidRegex: ^DedicatedServerMod\.Shared$
    type: Namespace
- include:
    uidRegex: ^DedicatedServerMod\.Shared\.Configuration$
    type: Namespace
- include:
    uidRegex: ^DedicatedServerMod\.Shared\.Networking$
    type: Namespace
- include:
    uidRegex: ^DedicatedServerMod\.Shared\.Permissions$
    type: Namespace
- exclude:
    uidRegex: ^DedicatedServerMod\.Shared\.Networking\.MessageRouter$
    type: Type
