export type RuntimeTarget = "il2cpp" | "mono";

export type AuthProvider = "SteamGameServer" | "None";

export type MessagingBackend = "FishNetRpc" | "SteamNetworkingSockets";

export type StdioConsoleMode = "Auto" | "Enabled" | "Disabled";

export type ServerConfigDraft = {
  runtime: RuntimeTarget;
  serverName: string;
  serverDescription: string;
  maxPlayers: number;
  serverPort: number;
  serverPassword: string;
  saveGamePath: string;
  authProvider: AuthProvider;
  authTimeoutSeconds: number;
  modVerificationEnabled: boolean;
  blockKnownRiskyClientMods: boolean;
  allowUnpairedClientMods: boolean;
  strictClientModMode: boolean;
  steamGameServerLogOnAnonymous: boolean;
  steamGameServerQueryPort: number;
  steamGameServerMode: "Authentication" | "AuthenticationAndSecure" | "NoAuthentication";
  messagingBackend: MessagingBackend;
  steamNetworkingSocketsVirtualPort: number;
  tcpConsoleEnabled: boolean;
  tcpConsoleBindAddress: string;
  tcpConsolePort: number;
  tcpConsoleRequirePassword: boolean;
  tcpConsolePassword: string;
  stdioConsoleMode: StdioConsoleMode;
  webPanelEnabled: boolean;
  webPanelBindAddress: string;
  webPanelPort: number;
  webPanelOpenBrowserOnStart: boolean;
  webPanelExposeLogs: boolean;
  ignoreGhostHostForSleep: boolean;
  timeProgressionMultiplier: number;
  allowSleeping: boolean;
  pauseGameWhenEmpty: boolean;
  autoSaveEnabled: boolean;
  autoSaveIntervalMinutes: number;
  autoSaveOnPlayerJoin: boolean;
  autoSaveOnPlayerLeave: boolean;
  targetFrameRate: number;
};

export const DEFAULT_CONFIG_DRAFT: ServerConfigDraft = {
  runtime: "il2cpp",
  serverName: "Schedule One Dedicated Server",
  serverDescription: "A dedicated server for Schedule I",
  maxPlayers: 16,
  serverPort: 38465,
  serverPassword: "",
  saveGamePath: "",
  authProvider: "SteamGameServer",
  authTimeoutSeconds: 60,
  modVerificationEnabled: true,
  blockKnownRiskyClientMods: true,
  allowUnpairedClientMods: true,
  strictClientModMode: false,
  steamGameServerLogOnAnonymous: true,
  steamGameServerQueryPort: 27016,
  steamGameServerMode: "Authentication",
  messagingBackend: "FishNetRpc",
  steamNetworkingSocketsVirtualPort: 0,
  tcpConsoleEnabled: false,
  tcpConsoleBindAddress: "127.0.0.1",
  tcpConsolePort: 4050,
  tcpConsoleRequirePassword: true,
  tcpConsolePassword: "",
  stdioConsoleMode: "Auto",
  webPanelEnabled: false,
  webPanelBindAddress: "127.0.0.1",
  webPanelPort: 4051,
  webPanelOpenBrowserOnStart: true,
  webPanelExposeLogs: true,
  ignoreGhostHostForSleep: true,
  timeProgressionMultiplier: 1,
  allowSleeping: true,
  pauseGameWhenEmpty: true,
  autoSaveEnabled: true,
  autoSaveIntervalMinutes: 5,
  autoSaveOnPlayerJoin: true,
  autoSaveOnPlayerLeave: true,
  targetFrameRate: 60,
};

export function generateServerConfigToml(config: ServerConfigDraft): string {
  const lines: string[] = [
    "# DedicatedServerMod server configuration generated by s1servers.com.",
    "# Review provider-specific ports and paths before opening the server publicly.",
    "",
    "[server]",
    tomlString("serverName", config.serverName),
    tomlString("serverDescription", config.serverDescription),
    tomlNumber("maxPlayers", clampInteger(config.maxPlayers, 1, 64)),
    tomlNumber("serverPort", clampInteger(config.serverPort, 1024, 65535)),
    tomlString("serverPassword", config.serverPassword),
    "",
    "[storage]",
    "# Leave empty to use UserData/DedicatedServerSave.",
    tomlString("saveGamePath", config.saveGamePath),
    "",
    "[authentication]",
    tomlString("authProvider", config.authProvider),
    tomlNumber("authTimeoutSeconds", clampInteger(config.authTimeoutSeconds, 1, 120)),
    tomlBoolean("modVerificationEnabled", config.modVerificationEnabled),
    tomlNumber("modVerificationTimeoutSeconds", 20),
    tomlBoolean("blockKnownRiskyClientMods", config.blockKnownRiskyClientMods),
    tomlBoolean("allowUnpairedClientMods", config.allowUnpairedClientMods),
    tomlBoolean("strictClientModMode", config.strictClientModMode),
    tomlBoolean("steamGameServerLogOnAnonymous", config.steamGameServerLogOnAnonymous),
    tomlString("steamGameServerToken", ""),
    tomlNumber("steamGameServerQueryPort", clampInteger(config.steamGameServerQueryPort, 1024, 65535)),
    tomlString("steamGameServerMode", config.steamGameServerMode),
    "",
    "[messaging]",
    tomlString("messagingBackend", config.messagingBackend),
    tomlNumber("steamNetworkingSocketsVirtualPort", clampInteger(config.steamNetworkingSocketsVirtualPort, 0, 65535)),
    tomlNumber("steamNetworkingSocketsMaxPayloadBytes", 1200),
    tomlString("steamNetworkingSocketsServerSteamId", ""),
    "",
    "[tcpConsole]",
    tomlBoolean("tcpConsoleEnabled", config.tcpConsoleEnabled),
    tomlString("tcpConsoleBindAddress", config.tcpConsoleBindAddress),
    tomlNumber("tcpConsolePort", clampInteger(config.tcpConsolePort, 1024, 65535)),
    tomlNumber("tcpConsoleMaxConnections", 3),
    tomlBoolean("tcpConsoleRequirePassword", config.tcpConsoleRequirePassword),
    tomlString("tcpConsolePassword", config.tcpConsolePassword),
    tomlString("stdioConsoleMode", config.stdioConsoleMode),
    "",
    "[webPanel]",
    tomlBoolean("webPanelEnabled", config.webPanelEnabled),
    tomlString("webPanelBindAddress", config.webPanelBindAddress),
    tomlNumber("webPanelPort", clampInteger(config.webPanelPort, 1024, 65535)),
    tomlBoolean("webPanelOpenBrowserOnStart", config.webPanelOpenBrowserOnStart),
    tomlNumber("webPanelSessionMinutes", 120),
    tomlBoolean("webPanelExposeLogs", config.webPanelExposeLogs),
    "",
    "[gameplay]",
    tomlBoolean("ignoreGhostHostForSleep", config.ignoreGhostHostForSleep),
    tomlNumber("timeProgressionMultiplier", clampNumber(config.timeProgressionMultiplier, 0, 24)),
    tomlBoolean("allowSleeping", config.allowSleeping),
    tomlBoolean("pauseGameWhenEmpty", config.pauseGameWhenEmpty),
    tomlString("freshSaveQuestBootstrapMode", "StartFromBeginning"),
    "",
    "[autosave]",
    tomlBoolean("autoSaveEnabled", config.autoSaveEnabled),
    tomlNumber("autoSaveIntervalMinutes", clampNumber(config.autoSaveIntervalMinutes, 1, 1440)),
    tomlBoolean("autoSaveOnPlayerJoin", config.autoSaveOnPlayerJoin),
    tomlBoolean("autoSaveOnPlayerLeave", config.autoSaveOnPlayerLeave),
    "",
    "[logging]",
    "enabledLoggingOptions = []",
    "enablePerformanceMonitoring = false",
    "",
    "[performance]",
    tomlNumber("targetFrameRate", clampInteger(config.targetFrameRate, -1, 300)),
    "vSyncCount = 0",
    "",
  ];

  return lines.join("\n");
}

function tomlString(key: string, value: string) {
  return `${key} = ${formatTomlString(value)}`;
}

function tomlNumber(key: string, value: number) {
  return `${key} = ${Number.isInteger(value) ? value.toString() : value.toFixed(2).replace(/\.?0+$/, "")}`;
}

function tomlBoolean(key: string, value: boolean) {
  return `${key} = ${value ? "true" : "false"}`;
}

function formatTomlString(value: string) {
  if (!value.includes("'")) {
    return `'${value}'`;
  }

  return `"${value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t")}"`;
}

function clampInteger(value: number, min: number, max: number) {
  return Math.min(max, Math.max(min, Math.round(Number.isFinite(value) ? value : min)));
}

function clampNumber(value: number, min: number, max: number) {
  return Math.min(max, Math.max(min, Number.isFinite(value) ? value : min));
}
